/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libIO_lib_CalculadoraColas */

#ifndef _Included_libIO_lib_CalculadoraColas
#define _Included_libIO_lib_CalculadoraColas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libIO_lib_CalculadoraColas
 * Method:    calculasls
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_libIO_lib_CalculadoraColas_calculasls
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     libIO_lib_CalculadoraColas
 * Method:    calcularlq
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_libIO_lib_CalculadoraColas_calcularlq
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     libIO_lib_CalculadoraColas
 * Method:    calcularws
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_libIO_lib_CalculadoraColas_calcularws
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     libIO_lib_CalculadoraColas
 * Method:    calcularwq
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_libIO_lib_CalculadoraColas_calcularwq
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     libIO_lib_CalculadoraColas
 * Method:    calcularp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_libIO_lib_CalculadoraColas_calcularp
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     libIO_lib_CalculadoraColas
 * Method:    calcularp0
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_libIO_lib_CalculadoraColas_calcularp0
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     libIO_lib_CalculadoraColas
 * Method:    calcularpn
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_libIO_lib_CalculadoraColas_calcularpn
  (JNIEnv *, jobject, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
