/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libAnalisisN_lib_CalculadoraNewtonRaphon */

#ifndef _Included_libAnalisisN_lib_CalculadoraNewtonRaphon
#define _Included_libAnalisisN_lib_CalculadoraNewtonRaphon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libAnalisisN_lib_CalculadoraNewtonRaphon
 * Method:    newton_raphson
 * Signature: (IF)F
 */
JNIEXPORT jfloat JNICALL Java_libAnalisisN_lib_CalculadoraNewtonRaphon_newton_1raphson
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     libAnalisisN_lib_CalculadoraNewtonRaphon
 * Method:    error
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_libAnalisisN_lib_CalculadoraNewtonRaphon_error
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
